POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvZTMiLCJpZCI6IjY2OWQ4MDg4MDE5OTEyODFjZTQ3ZGNjMyIsImlhdCI6MTcyMTU5ODIyMCwiZXhwIjoxNzIxNjAxODIwfQ.dSLsz88ePFDxBEqsBoVHAgAEjKMkas-YjTV1v_Th4pE

{
  "title": "Top 10 ReactJS Tips and Tricks for Beginners",
  "author": "Williams Peter",
  "url": "https://medium.com/@ghostsmaw/top-10-reactjs-tips-and-tricks-for-beginners-4edb8db3e824",
  "likes": 55
}


###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Learning Functional Programming with Scala",
  "author": "Ryan Susana",
  "url": "https://ryansusana.medium.com/learning-functional-programming-with-scala-ccc7bf68214f",
  "likes": 99,
  "user": "669d30f99152d457f5002430"
}


###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Why use Scala for building backend applications?",
  "author": "JAROSLAV REGEC",
  "url": "https://scalac.io/blog/why-use-scala/",
  "likes": 1,
  "user": "669d30f99152d457f5002430" 
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Ruby on Rails — July 2024",
  "author": "Sajjad Umar",
  "url": "https://medium.com/@sajjadumar/ruby-on-rails-july-2024-d73e4b2e3394",
  "likes": 0 
}
